port 26379
bind 0.0.0.0
protected-mode no
dir /tmp
sentinel monitor queuebit-primary redis-primary 6379 2
sentinel down-after-milliseconds queuebit-primary 1000
sentinel failover-timeout queuebit-primary 15000
sentinel parallel-syncs queuebit-primary 1
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
